### PR TITLE
compiler-rt is no more

### LINKED ISSUE #2: libcompiler-rt on 3ds
This isn't directly related to this project, but in order to continue development on the 3DS in Rust, we need a libcompiler-rt.a compiled in such a way that it can be linked with arm-none-eabi-gcc. This is a show stopper once you get past very trivial code, because llvm emits calls into it for its intrinsics.

If someone has experience with that, contributions would be helpful. We can't really advance until that problem is resolved.

### PR DESCRIPTION
**Pull request by FenrirWolf**
The creation of [rustc-builtins](https://github.com/japaric/rustc-builtins) means that we can finally drop our dependency on `compiler-rt`. The only catch is that enabling LTO seems to cause linker issues in `rustc-builtins`. I'm going to file an issue reporting the problem, but for now disabling LTO results in a successful build.

Fixes #2

### CODE REVIEW

**Comment by HybridEidolon** [comment]
Oh wow, I am really excited to take a look at this.

Have you been able to test that it works for the most part? Are there any missing intrinsics?

**Comment by FenrirWolf** [comment]
No intrinsics seem to be missing from what I can tell. But a new problem is that the build script for `rustc-builtins` was changed and now it keeps crashing.

**Comment by FenrirWolf** [comment]
Seems to be the same issue as this: https://github.com/japaric/rustc-builtins/issues/87

**Comment by HybridEidolon** [comment]
Let's wait on that issue until it's fixed before making it a default behavior in the template and library.

**Pull request closed without merging**
