### PR TITLE
Fix unsoundness in Console's API

### PR DESCRIPTION
**Pull request by FenrirWolf**
A bit of a smaller PR this time around =P

It turns out that libctru expects `PrintConsole` structs to be immovable. Or rather, you can copy them around but then you have to manually `consoleSelect()` the new copy. If you don't do that and you try printing to an old console context that went out of scope, that's a dangling pointer deref.

To fix that, we go ahead and just box up the inner context. Users can move `Console` structs wherever they want while the inner `PrintConsole` data remains at a fixed address.

I also made a few changes to some of the other methods. `select` and `clear`, while they modify state internal to libctru, are essentially immutable from Rust's perspective, so I think it's sound to access them with `&self` rather than `&mut self`

One thing in particular I'd like feedback on is the `set_window` function. As far as I'm aware it does no bounds checking on its inputs at all. When faced with how to handle that, I had a few different options at my disposal:
1) Use the Builder Pattern to safely support giving consoles a custom, bounds-checked size before initializing them.
2) Make the function `unsafe` and let the end-user deal with bounds issues.
3) Don't include the function at all. Instead, offer an `as_raw` method that gives a pointer to the underlying `PrintConsole`. A user who cares about customizing the window size can take that pointer and pass it directly to `consoleSetWindow()` via `ctru-sys`.

Setting the console size is a rare enough thing that I opted not to bother with 1), but 2) and 3) both seem like viable alternatives and I'm curious which method we should prefer both for this situation and for similar cases should they arise in other APIs. I'm kinda leaning in the direction of 3), myself

### CODE REVIEW

**Review by panicbit — APPROVED** [review]
Looks good. Libstd does the same for mutexes to avoid them being moved.

**Comment by panicbit** [comment]
Regarding the `set_window` stuff I'd prefer a combination of 1. and 3.: A default constructor, a builder-pattern based API to allow for customization and a way to get the raw pointer to allow doing anything that is not covered by the Rust API yet.

> I also made a few changes to some of the other methods. select and clear, while they modify state internal to libctru, are essentially immutable from Rust's perspective, so I think it's sound to access them with &self rather than &mut self

I've noticed that the console API is [not really thread safe](https://github.com/smealum/ctrulib/blob/29418f4d3d1d92bb39eacf855a9fa935ff07b45b/libctru/source/console.c#L591-L597). Ideally the `currentConsole` would be guarded by a Mutex and a lock would need to be held to print stuff (otherwise a thread could switch the console midway while another thread is printing). I'm not sure wether we should really bother with this or not.

**Comment by panicbit** [comment]
It probably makes sense to at least ensure that the `set_window` values are at least 0, otherwise this one is probably going to overflow a little bit https://github.com/smealum/ctrulib/blob/29418f4d3d1d92bb39eacf855a9fa935ff07b45b/libctru/source/console.c#L89

**Comment by FenrirWolf** [comment]
I merged things as-is for now, but we can change it to a builder pattern in another PR

**Pull request merged**
