### PR TITLE
ctr-std: add time module

### PR DESCRIPTION
**Pull request by FenrirWolf**
devkitARM doesn't seem to have any support for monotonic time functions, so both SystemTime and Instant are initialized with the gettimeofday(2) syscall. Hopefully this won't cause any problems.

### CODE REVIEW

**Comment by HybridEidolon** [comment]
The system call [`GetSystemTick`][GetSystemTick] can be used as a monotonic time source. Unfortunately, if you want _easy_ access to it, you would need to link in ctru-rs into ctr-std. I don't think this is the best approach, and perhaps using a local naked function that emits the `svc` instruction ala [the ctrulib wrapper][ctrulib] would be better. Or even an alternate pure-Rust library for accessing these system calls which ctr-std would link in and use.

The length of a tick depends on the CPU in consideration, but ticks should never wrap around regardless. I think it would be best to get a _correct_ impl on Instant in this way.

[GetSystemTick]: https://www.3dbrew.org/wiki/SVC
[ctrulib]: https://github.com/smealum/ctrulib/blob/4abf42f16dd6c101b32a9d152a40fa6d3cb239ed/libctru/source/svc.s#L232

**Comment by HybridEidolon** [comment]
You can read [`PDN_MPCORE_CLKCNT`][pdn] from address `0x10141300` (u16) to get ARM11 CPU state, which is the CPU `GetSystemTick` sources from (I thought it considered ARM9 as well but I was mistaken).

On O3DS this will always be `0x0000` but on N3DS, 0 means the CPU is in 268MHz (1x) mode. The wiki on the register gives some info on the bit flags set here.

However, it is not clear to me what would happen if `KernelSetState` were called -- if that would adjust the tick counter or what. The number itself is monotonic but converting to nanoseconds between two Instants might be incorrect if a clock change happened in that span. Not sure if there's a correct way to deal with that either?

[pdn]: https://www.3dbrew.org/wiki/PDN_Registers#PDN_MPCORE_CLKCNT

**Comment by FenrirWolf** [comment]
linking ctru-rs into ctr-std would definitely not work, as that would lead into a circular dependency situation and that sounds like it would end in tragedy. Linking in ctru-*sys*, however, might be possible, and might even be required when the time comes to implement things like `std::thread`. Though a pure Rust syscall crate would likely do the trick as well.

**Comment by FenrirWolf** [comment]
So, adding a dependency on ctru-sys to ctr-std turned out to be pretty painless. We can still pursue the idea of a pure Rust syscall layer if you feel that would be a better fit, though in my opinion including a direct dependency on ctru-sys makes sense. If anything it formalizes the notion that ctr-std and libctru are already intertwined to begin with, given that various C syscalls like `write` and `gettimeofday` are defined in newlib yet actually implemented in libctru

**Comment by FenrirWolf** [comment]
Also I'm pretty sure that the current impl for Instant is bugged, so don't merge yet either way.

**Comment by FenrirWolf** [comment]
I think that Instant is working correctly now, but I'm not so sure about SystemTime. Compare this [playground example](https://is.gd/qBeeC5) with an equivalent [3DS example](http://pastebin.com/ytWkkqL3).

The Playground version prints `SystemTime: Duration { secs: 2, nanos: 128057 }` while on 3DS I get `SystemTime: Duration { secs: 1, nanos: 999936000 }`, which shouldn't be happening after the thread sleeps for 2 seconds.

SystemTime is sourced from `gettimeofday()`, whose implementation lives [here](https://github.com/smealum/ctrulib/blob/master/libctru/source/os.c#L80), and I'm not completely sure if the issue lies with that function or with code on the Rust side. But I suspect the issue is with some constants defined on the C side.

**Comment by FenrirWolf** [comment]
Okay, `gettimeofday()`'s accuracy is now fixed in upstream libctru. I also overhauled the implementation for Instant yet again to give it a similar accuracy fix. As far as I can tell this should be ready to merge now.

**Comment by FenrirWolf** [comment]
rebased to fix merge conflict

**Review by HybridEidolon — APPROVED** [review]

**Pull request merged**
