### PR TITLE
Display panics via the Error applet

### PR DESCRIPTION
**Pull request by FenrirWolf**
Makes panics look like this:

Yay for applets!

Citra doesn't currently like the error applet, but it works fine on console.

### CODE REVIEW

**Comment by HybridEidolon** [comment]
Nice, looks fresh as hell. Is it possible to put the old behavior behind a feature flag for debugging in citra while they work on system dialogs?

**Comment by FenrirWolf** [comment]
Okay, I added Citra compatibility. If you were building the template project, you'd enable it by modifying `Xargo.toml` like so:

```
[dependencies.collections]
[dependencies.rand]

[dependencies.std]
git = "https://github.com/rust3ds/ctru-rs"
features = ["citra"]
stage = 1
```

Also, the CI failure is because https://github.com/rust3ds/alloc_system3ds/pull/4 still needs to be merged.

I can push again afterwards to test the integration.

**Comment by HybridEidolon** [comment]
I merged the change from rust3ds/alloc_system3ds#4 now. Try pushing again?

**Comment by FenrirWolf** [comment]
Build succeeded this time, but apparently CI is running the libstd unit tests too and those didn't compile.

tbh I'm not sure if libstd's tests will work in this configuration, given that they depend on threading and unwinding to operate, and we have a custom API for the former and currently lack the latter.

Also, `cargo test` is for compiling and testing on the host platform. Even if they did compile, they would have to be cross-compiled via Xargo and tested via Citra or something.

**Comment by FenrirWolf** [comment]
In fact, I'm quite certain that they won't work at all, since they can also depend on linux-style environment variables or test features that we won't ever have like launching child processes. Maybe we could set up something like [utest](https://github.com/japaric/utest) at some point, but that's a story for another PR.

Either way, I feel like we shouldn't block on/perform CI on unit tests for now.

cc @panicbit re: CI stuff

**Comment by HybridEidolon** [comment]
Yeah. We should fix that in another PR, though. I think this one looks good so I'll go ahead and merge it.

**Pull request merged**
