### PR TITLE
Standard Library support (sort of)

### PR DESCRIPTION
**Pull request by FenrirWolf**
So, I did a thing over the past few days. Presenting [ctr-std](https://github.com/FenrirWolf/ctr-std). It's mainly just a reexport of the freestanding crates generated by Xargo, with enough pieces cherry-picked from the Standard Library and LibRedox to hold it in one piece. I honestly don't know if I should be proud of myself or terrified by the prospect of using it.

So if you think it's worth pursuing further, this PR adds ctr-std compatibility to ctru-rs.  On the one hand, I feel this can be beneficial because there are certain things (such as file descriptors) that aren't necessarily defined by libctru and would make more sense to implement in ctr-std than in ctru-rs. But on the other hand, I wonder if this adds too much complexity and if it would be better to just define those kinds of features in ctru-rs instead. Either way, I'm curious what you think.

### CODE REVIEW

**Comment by HybridEidolon** [comment]
So, I'm hesitating on merging this until I make a decision on this, but I am planning on making a GitHub organization to hold all the rust 3ds-related projects. I still can't do any 3DS dev until smea creates a ninjhax payload for firmware 11, so it's on the backburner personally, but I think in the end it would be easier to just have all of them in one place and so that someone else can help with maintaining the projects.

**Comment by FenrirWolf** [comment]
That makes sense to me. Right now things are a bit ad-hoc with dependencies linking to one github profile or another, and having a canonical location for everything (since I'm not sure this is all quite suited for crates.io) would be pretty nice.

**Comment by HybridEidolon** [comment]
I'm still not sure about this, and I'm wondering if I can get some input from at least one more person on it. The problem is that if we introduce a dependency on a re-exporting crate, then user crates are expected to use it as well. Should std ever be fully supported on 3DS, this will introduce naming confusion for end-users using ctr-std. It's a different situation than alloc_system3ds, where only the application crate has to import it and could also choose to provide another or its own implementation.

For users to simply use core and collections, even if libstd support were introduced, end users would not have to change their code to accommodate a deprecated ctr-std, since core is stabilized now.

That isn't to say people couldn't themselves _choose_ to use ctr-std within their application code, but I think that ctru-rs should leave it out as not to add an unnecessary dependency.

By the way, you've been added as a read-access member of a new org. If you have any rust3ds-related libraries you want to move over, you can if you feel like it.

**Comment by FenrirWolf** [comment]
That's fine. After playing with it some more I'm not all that certain it should be a default dependency either. It's big, complex, partially working, and definitely nonstandard. So at this point my vote would actually be _not_ to merge.

And it's also a lesson on why I should do pull requests from a branch and not from master, so there's that too. <_<

**Comment by HybridEidolon** [comment]
Yeah, I don't think this makes sense inside the ctru-rs library code. Perhaps examples can make use of it (dev dependency), but let's avoid it at the wrapper layer.

**Pull request closed without merging**
