### PR TITLE
Add Travis CI

### PR DESCRIPTION
**Pull request by panicbit**
Don't forget to go to https://travis-ci.org/ and activate this repo.

### CODE REVIEW

**Comment by HybridEidolon** [comment]
Does this work without the devkitarm toolchain? Is it just for a compilation smoke test?

**Comment by panicbit** [comment]
It works without devkitArm and just checks that the code compiles at all (not that it links properly or anything).
However, the CI config for rust3ds-template installs the toolchain and produces a binary at the end.

**Comment by HybridEidolon** [comment]
It's configured in travis-ci.org now, ready for next push.

**Comment by panicbit** [comment]
Nice :+1:

**Pull request merged**
