### PR TITLE
Recreate ctr-std from the ground up

### PR DESCRIPTION
**Pull request by FenrirWolf**
Our version of `std` was both hopelessly out of date and also rather hacky because of some questionable decisions I'd made when I first ported the thing, so I figured it was time to start over again. Shoutouts to the `wasm` target for providing a bunch of stubs that made adapting things easier this time around!

Hopefully these changes will make it easier to implement missing `std` functionality too. For example, I made an attempt at getting network support up and running, but there are still some pieces that I haven't figured out or that seem to be missing altogether from devkitARM and/or libctru (such as anything to do with IPv6). But this time I made sure to tag any questionable hacks I made to get around that with TODO comments, so they should be easier to notice and (hopefully) to eventually remove :smile:

### CODE REVIEW

**Comment by FenrirWolf** [comment]
Travis is failing because of dumb sysroot stuff. Working to see if I can get around that.

**Comment by FenrirWolf** [comment]
Cool, got it all working. Some of our internal dependencies run the `libc_shim` crate for us, so we can just make sure that all of our custom sysroot crates use `feature(libc)]` instead of explicitly depending on `libc`. Had to push a change to our [alloc_system impl](https://github.com/rust3ds/alloc_system3ds/commit/651d1652476382e824dcbeb718577408a621c994) too.

**Comment by HybridEidolon** [comment]
oh god that's a big diff

**Comment by FenrirWolf** [comment]
lol sorry about that. its hard to modularize commits to std since it's a big ball of intertwined dependencies. you just kinda have to hack at it until the compiler errors go away

**Pull request merged**
